/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'garriguv' at '1/10/16 6:25 PM' with Gradle 2.10
 *
 * @author garriguv, @date 1/10/16 6:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
